FROM gcr.io/wise-cycling-267806/alignment-base
WORKDIR /home/bioinfo/alignment/

RUN curl -LO https://storage.googleapis.com/bioinfostudio/alignment/data/SM_Blood_ID_ERR059356.subset_R1.fastq.gz
RUN curl -LO https://storage.googleapis.com/bioinfostudio/alignment/data/SM_Blood_ID_ERR059356.subset_R2.fastq.gz

WORKDIR /home/bioinfo/
